theme: jekyll-theme-minimal
title: Matthieu Muffato
logo: assets/img/canard.png
description: Welcome !

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: true
