theme: jekyll-theme-minimal
title: Matthieu Muffato
logo: https://s.gravatar.com/avatar/27c2b50492d64ec9aaec05720fe588c1?s=200
description: Welcome !

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: true
